// GOLDEN SNAPSHOT of the pre-refactor webview quota functions.
// Generated by scripts/make-quota-golden.js from the original webview
// bodies (kept in quota-golden.js / webview/main.js). test-quota-core.js
// compares the shared bundle against these. DO NOT edit by hand.

const K_CAPACITY_RATIOS = Object.freeze({
  opus: 4.5,
  antigravity: 5.0,
  codex: 4.0,
  claude: 4.5,
});
const K_DEFAULT_RATIO = 4.5;

function toFiniteNumber(value) {
  const number = Number(value);
  return Number.isFinite(number) && number >= 0 ? number : 0;
}

function clamp(value, min, max) {
  const number = Number(value);
  return Number.isFinite(number) ? Math.min(Math.max(number, min), max) : min;
}

function capacityTone(percentage) {
  return percentage <= 15 ? "critical" : percentage <= 35 ? "warning" : "healthy";
}

function calculateEffective5HourQuota(fiveHourPct, weeklyPct, prefix) {
  const modelKey = prefix.toLowerCase().replace(/weekly/i, "");
  const K = K_CAPACITY_RATIOS[modelKey] ?? K_DEFAULT_RATIO;

  if (weeklyPct === 0) {
    return {
      effectivePct: 0.0,
      isWeeklyExhausted: true,
      isWeeklyCapped: true,
      K,
    };
  }

  if (typeof weeklyPct === "number" && Number.isFinite(weeklyPct)) {
    const weeklyCeiling = weeklyPct * K;
    if (weeklyCeiling < fiveHourPct) {
      return {
        effectivePct: clamp(weeklyCeiling, 0, 100),
        isWeeklyExhausted: false,
        isWeeklyCapped: true,
        K,
      };
    }
  }

  return {
    effectivePct: fiveHourPct,
    isWeeklyExhausted: false,
    isWeeklyCapped: false,
    K,
  };
}

function formatRefreshCountdown(value) {
  if (!value) return undefined;
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return undefined;
  
  const diffMs = date.getTime() - Date.now();
  if (diffMs <= 0) return { full: "\u00B7 Refreshes soon", medium: "\u00B7 Soon", short: "\u00B7 Soon" };
  
  const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
  const diffMins = Math.floor((diffMs % (1000 * 60 * 60)) / (1000 * 60));
  
  if (diffHours >= 24) {
    return {
      full: `\u00B7 Refreshes in ${diffHours}h ${diffMins}m`,
      medium: `\u00B7 ${diffHours}h`,
      short: `\u00B7 ${diffHours}h`,
    };
  }
  if (diffHours > 0) {
    return {
      full: `\u00B7 Refreshes in ${diffHours}h ${diffMins}m`,
      medium: `\u00B7 ${diffHours}h ${diffMins}m`,
      short: `\u00B7 ${diffHours}h`,
    };
  }
  return {
    full: `\u00B7 Refreshes in ${diffMins}m`,
    medium: `\u00B7 ${diffMins}m`,
    short: `\u00B7 ${diffMins}m`,
  };
}

function formatNumber(value) {
  return new Intl.NumberFormat().format(toFiniteNumber(value));
}

function formatTokenCount(value) {
  const number = toFiniteNumber(value);
  if (number >= 1_000_000) {
    return `${(number / 1_000_000).toFixed(number >= 10_000_000 ? 1 : 2)}M tokens`;
  }
  if (number >= 1_000) {
    return `${(number / 1_000).toFixed(number >= 10_000 ? 1 : 2)}K tokens`;
  }
  return `${formatNumber(number)} tokens`;
}

function formatResetTime(value) {
  if (!value) return undefined;
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return String(value);
  }
  const diffHours = (date.getTime() - Date.now()) / (1000 * 60 * 60);
  if (diffHours > 24) {
    return date.toLocaleString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false });
  }
  return date.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit', hour12: false });
}

function buildTokenMetric(label, status, prefix, ariaLabel, pairedWeeklyPrefix) {
  const left = toFiniteNumber(status[`${prefix}TokensLeft`]);
  const max = toFiniteNumber(status[`${prefix}Max`]);
  const exactPercentage = status[`${prefix}Percentage`];
  const estimated = status[`${prefix}EstimatedAbsolute`];
  const rawResetTime = status[`${prefix}ResetTime`];

  let percentage;
  if (typeof exactPercentage === "number" && Number.isFinite(exactPercentage)) {
    percentage = clamp(exactPercentage, 0, 100);
  } else if (max > 0) {
    percentage = clamp((left / max) * 100, 0, 100);
  }

  const hasAbsolute = typeof estimated === "number" || max > 0 || left > 0;
  let normalizedPercentage = percentage ?? 0;
  let isWeeklyExhausted = false;
  let isWeeklyCapped = false;
  let capReason = "";

  // Dual-Window Quota Synchronization: 5Hours constrained by Weekly
  if (label === "5Hours" && pairedWeeklyPrefix && percentage !== undefined) {
    const weeklyExact = status[`${pairedWeeklyPrefix}Percentage`];
    const weeklyLeft = toFiniteNumber(status[`${pairedWeeklyPrefix}TokensLeft`]);
    const weeklyMax = toFiniteNumber(status[`${pairedWeeklyPrefix}Max`]);
    let weeklyPct = typeof weeklyExact === "number" && Number.isFinite(weeklyExact)
      ? clamp(weeklyExact, 0, 100)
      : weeklyMax > 0 ? clamp((weeklyLeft / weeklyMax) * 100, 0, 100) : undefined;

    if (weeklyPct !== undefined) {
      const sync = calculateEffective5HourQuota(normalizedPercentage, weeklyPct, prefix);
      normalizedPercentage = sync.effectivePct;
      isWeeklyExhausted = sync.isWeeklyExhausted;
      isWeeklyCapped = sync.isWeeklyCapped;
      if (isWeeklyExhausted) {
        capReason = "Weekly exhausted";
      } else if (isWeeklyCapped) {
        capReason = `Weekly capped (${weeklyPct.toFixed(1)}% × ${sync.K})`;
      }
    }
  }
  
  const displayPercentage = isWeeklyExhausted ? 0.0 : normalizedPercentage;
  const mainText = (hasAbsolute || percentage !== undefined) ? `${displayPercentage.toFixed(2)}%` : "Unavailable";
  
  let subtextFull = "Waiting for quota data";
  let subtextMedium = "Waiting";
  let subtextShort = "Waiting";
  if (hasAbsolute || percentage !== undefined) {
    subtextFull = `${normalizedPercentage.toFixed(2)}% remaining`;
    subtextMedium = `${normalizedPercentage.toFixed(2)}%`;
    subtextShort = `${normalizedPercentage.toFixed(1)}%`;
  }

  let effectiveResetTime = rawResetTime;
  if (isWeeklyExhausted && pairedWeeklyPrefix) {
    const pairedResetTime = status[`${pairedWeeklyPrefix}ResetTime`];
    if (pairedResetTime) {
      effectiveResetTime = pairedResetTime;
    }
  }

  const countdown = formatRefreshCountdown(effectiveResetTime);
  const refreshFull = countdown ? countdown.full : "";
  const refreshMedium = countdown ? (countdown.medium || countdown.short) : "";
  const refreshShort = countdown ? countdown.short : "";
  
  let tooltip = `${ariaLabel || label}: ${subtextFull}${refreshFull ? ` ${refreshFull}` : ""}. Healthy: over 35%. Caution: 15-35%. Limited: 15% or lower.`;
  if (isWeeklyExhausted) {
    tooltip = `${ariaLabel || label}: 0.00% remaining (Weekly quota is exhausted${refreshFull ? ` · ${refreshFull}` : ""}). All 5-hour capacity is locked until weekly reset.`;
  } else if (isWeeklyCapped) {
    tooltip = `${ariaLabel || label}: ${subtextFull} (${capReason}). 5-hour capacity is constrained by remaining weekly budget.`;
  }

  const labelFull = label;
  const labelMedium = label;
  const labelShort = label === "5Hours" ? "5H" : label === "Weekly" ? "W" : label;

  return {
    label,
    labelFull,
    labelMedium,
    labelShort,
    ariaLabel: ariaLabel || label,
    mainText,
    subtext: subtextFull,
    subtextFull,
    subtextMedium,
    subtextShort,
    refreshText: refreshFull,
    refreshFull,
    refreshMedium,
    refreshShort,
    percentage: normalizedPercentage,
    unavailable: percentage === undefined && !hasAbsolute,
    tone: capacityTone(normalizedPercentage),
    tooltip,
    isWeeklyExhausted,
    isWeeklyCapped,
  };
}

function capacitySummaryEntry(labelFull, labelMedium, labelShort, exactPercentage, left, max) {
  let percentage;
  if (typeof exactPercentage === "number" && Number.isFinite(exactPercentage)) {
    percentage = clamp(exactPercentage, 0, 100);
  } else {
    const safeLeft = toFiniteNumber(left);
    const safeMax = toFiniteNumber(max);
    if (safeMax > 0) {
      percentage = clamp((safeLeft / safeMax) * 100, 0, 100);
    }
  }

  return typeof percentage === "number" ? { label: labelFull, labelFull, labelMedium, labelShort, percentage } : undefined;
}

module.exports = { K_CAPACITY_RATIOS, K_DEFAULT_RATIO, toFiniteNumber, clamp, capacityTone, calculateEffective5HourQuota, formatRefreshCountdown, formatNumber, formatTokenCount, formatResetTime, buildTokenMetric, capacitySummaryEntry };
